DROP DATABASE IF EXISTS TeacherAi;

CREATE DATABASE TeacherAi;

USE TeacherAi;

CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE book (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  fileUrl VARCHAR(255) NOT NULL,
  uploadDate DATETIME NOT NULL
);